- name: Add repo from file
  block:
   - name: Download ODL zypper repo
     get_url:
       url: "{{ suse_rpm_repo_url }}"
       dest: /tmp/opendaylight.repo
   - name: Add ODL zypper repo
     zypper_repository:
       repo: "/tmp/opendaylight.repo"
       auto_import_keys: yes
       disable_gpg_check: yes
       runrefresh: yes
  when: odl_version is defined

- name: Add ODL zypper repo
  zypper_repository:
    repo: "{{ suse_rpm_repo_url }}"
    name: opendaylight
    auto_import_keys: yes
    runrefresh: yes
  when: odl_version is undefined
